### ISSUE TITLE
Get rid of switches, that's a pretty hardcoded version. Adjust your rules to let game be more generic

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#10]
https://github.com/thirdiblind/Slot_Machine/blob/9079a1775528ef997e63bcacb8f0b249497826ad/Slot_Machine/Program.cs#L31-L33

I wrote your messages about your game rules. For me they seem a bit ackward to be honest. 1 means center, 2 means the rest of horizontal, and 3 everything?

What I don't like about it is, that this rules force you to have such a lot of hardcoded checks in your loops. The loops are a good way to have a generic solution, but if you again use a switch in the loops, checking for an exact row index, the generic solution is gone.
So what if you decide to enlarge your grid to 1000x1000? Won't be fun to program all your switch cases.

So what about, changing the rules a bit, so your code becomes more generic?
You could have
1 --> Center line: If user input 1 it means, only center line. So calculate the index of the center line, and use a loop to check if all values of this line match
2 --> horizontal lines, all. If you do it like this, you can just use a nested loop and check for any line to match. So in case of a 100x100 grid or 50x50, you will just loop through and check for matches.
3 -> all vertical lines
4 --> both diagonal

Try to get rid of this switches!

**Comment by thirdiblind** [comment]
This was a big lesson, I overcomplicated this. Simplifying and building for scale is the way to go. Thanks!!
