### ISSUE TITLE
Place if statements right

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#11]
https://github.com/thirdiblind/Slot_Machine/blob/9079a1775528ef997e63bcacb8f0b249497826ad/Slot_Machine/Program.cs#L189

First of all, the check of diagon lines is not in your while loop! So it is not part of your main game logic at all.
Second thing, you have this if, checking if user entered 3, but after you already did all winning checks on diagonal. Always try, to execute code only if really needed. 

So it makes more sense, to first check if userINput = 3 and only if this is the case, do all your checks.

And the checks for columns, so vertical lines, are done always? The whole nested loop is always executed and not somehow surrounded with any if? You only got this if inside your "if(isWin)" if statement:
 if (col == 1 || col == 2 || col == 3)  --> But col starts with 0 and ends with 2... and even if you correct it, what is it for, as col will be always 0-2?
So if you the checks for vertical lnes only executed if user input a certain choice, you need to first check on this and add a surrounding if-statement.

**Comment by thirdiblind** [comment]
I think this may not be necessary now that game logic has been simplified by removing switches and relying on for loops to the win logic.
