### ISSUE TITLE
Calculate the middle row index

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#13]
https://github.com/thirdiblind/Slot_Machine/blob/d0b13ae3085eecf6af014010b2bd7b76e4cf3aee/Slot_Machine/Program.cs#L109

Imagine, you extend your grid to 100x100, you could calculate the middle row index, instead of set it hardcoded.
At least, if not calculating, outsource it to a constant ;)

**Comment by thirdiblind** [comment]
Implemented center row calc, set to constant
