### ISSUE TITLE
Place your if statement better

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#14]
https://github.com/thirdiblind/Slot_Machine/blob/d0b13ae3085eecf6af014010b2bd7b76e4cf3aee/Slot_Machine/Program.cs#L142-L148

Currently, all of your winning logics are ALL executed always. Only the counting of winning rows is not executed, as you put it into the if statement. But all your loops etc. is anyway executed.

So can you imagine a better place how to/where to place this if condition `if(bet==2)` ?

This relates to all of your if conditions, center line, rows, columns and diagonals ;)

**Comment by thirdiblind** [comment]
Pushed to repo :)
