### ISSUE TITLE
Diagonal lines, counting of win / values compared

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#3]
https://github.com/thirdiblind/Slot_Machine/blob/de3ca64a7bde13d6306a82c9a56a0c26164d45f3/Slot_Machine/Program.cs#L94
https://github.com/thirdiblind/Slot_Machine/blob/de3ca64a7bde13d6306a82c9a56a0c26164d45f3/Slot_Machine/Program.cs#L103

https://github.com/thirdiblind/Slot_Machine/blob/de3ca64a7bde13d6306a82c9a56a0c26164d45f3/Slot_Machine/Program.cs#L111-L120

Still the logic is not yet 100% right. Here I added a short output of the indexes you try to access and compare for Right to Left diagonal:
![image](https://github.com/thirdiblind/Slot_Machine/assets/130921606/347f757a-c4a0-4346-9a87-28c2feaf3f0f)

So take a look at the logic for Right to left once again :)

And one thing you should consider is, that you increase your balance not for each matchin line, but for each time a value matches. So like you try to achieve it, you will always compare first element against second, second against third. So each time this is a match, the balance is increased, so twice in case of a whole matching row.

What you can do:
- Think about moving the if for checking if the diagonals match outside of your loop.
- Still, you reset your boolean variables each time to true, in each iteration. So if the first two values did not match, anyway you set the variable again to true in second iteration and if the second and third value match, the boolean flag says "yes cool, match". So the goal is to set the boolean flags for both diagonals before the loop once to true and set it to false in case of a mismatch. So it will be true after the loop only in case there was no mismatch in all three values

**Comment by thirdiblind** [comment]
Yes that is how I ended up solving the issue, moving those booleans and if statements outside the loop :) great advice!
