### ISSUE TITLE
Do you really need it and why?

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#4]
https://github.com/thirdiblind/Slot_Machine/blob/b5a4278226229f94f320f3e45c2768499be90231/Slot_Machine/Program.cs#L37-L60

Are you sure you want to keep this at all, and do you at least know how it works and what it is for?

**Comment by thirdiblind** [comment]
I took this as an opportunity to learn how to build a multi-choice selector as I'd been interested in this method of user input/selection. It was a neat opportunity to learn modulus and ternary operators and how they can be used for this purpose!
