### ISSUE TITLE
Make 1,2, 3 constants

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#5]
https://github.com/thirdiblind/Slot_Machine/blob/b5a4278226229f94f320f3e45c2768499be90231/Slot_Machine/Program.cs#L41

And please, get rid of all this hardcoded magic numbers. 1, 2, 3 you could define a minimum and maximum of lines to bet, store it in a constant and output to user "enter a value betwenn 1 and $max"

In general, think about it once again, if it is enough to make the user enter 1,2 or 3. Because in case of diagonal lines, 3 is not an option at all, there are only 2 lines to check on.

So maybe, you should better let user first choose which lines to play like "horizontal, vertical or diagonal" and based on that let the user enter how much, like 1, 2 in caseof diagonal or 1-3 in case of hor. and vert.

**Comment by thirdiblind** [comment]
Removed the hardcoded numbers where I could. 

We reviewed this in our conversation yesterday and made a determination that the game logic was that a bet of 1 would activate the center horizontal row, a bet of 2 would activate the center and bottom horizontal rows, and a bet of 3 would activate all rows. 

The wins according to this then would be as follows: A bet of 1 rewards the center horizontal row. A bet of 2 rewards the center and bottom horizontal row. The bet of 3 rewards all rows, including horizontal, vertical and diagonal lines.
