### ISSUE TITLE
Magic number --> Constant

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#6]
https://github.com/thirdiblind/Slot_Machine/blob/b5a4278226229f94f320f3e45c2768499be90231/Slot_Machine/Program.cs#L114 

Make 35 a constant! And please use it in every of your single outputs! Don't write it in there hardcoded :) ANd if you change the messages anyway, please go to use string interpolation instead of concatenation with the "+"

https://course.raketementoring.com/courses/rakete-mentoring/lectures/45560436

**Comment by thirdiblind** [comment]
Correction made. Pushing to repo @ 6/7pm central 11/13/23
