### ISSUE TITLE
No need for a switch, adjust your loop to run the right amount of times

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#7]
https://github.com/thirdiblind/Slot_Machine/blob/b5a4278226229f94f320f3e45c2768499be90231/Slot_Machine/Program.cs#L108-L131

And the switch is not the best choice, why? You already did so a good job having this nested loops for your winning check 🖤 For example, if the user chooses to play 2 lines, why having a switch? You could make adjust your loop to loop only 2 rows and not all three? So better modify the loop definition to work with the user input and thresholds

**Comment by thirdiblind** [comment]
We reviewed this together and agreed that a switch case is okay, but maybe not the best solution. I have removed it from the column win game logic.
