### ISSUE TITLE
Add better user instruction

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#8]
https://github.com/thirdiblind/Slot_Machine/blob/b5a4278226229f94f320f3e45c2768499be90231/Slot_Machine/Program.cs#L30

Even if you got this code block now, the user should get a bit more of information at the beginning. If "1, 2, 3" what is it you let him bet? For me it is not clear yet how the game logic works. So if user chooses 1, should only be one line played or only horizontal? So when I look at your horizontal winning check, it means to me, that user bets 1 and plays only first line, 2 means 1+2 and 3 all three.

But that means that the line type is not relevant? So if user bets 3 all 3 lines horz + vertical are played, and what about diagonal?

**Comment by thirdiblind** [comment]
This issue has been resolved in my most recent push to the repo. Thanks Mayisa
