### ISSUE TITLE
Message seems strange...

### ISSUE THREAD

**Issue by mayisa87** [thirdiblind/Slot_Machine#9]
https://github.com/thirdiblind/Slot_Machine/blob/b5a4278226229f94f320f3e45c2768499be90231/Slot_Machine/Program.cs#L199

You win horizontally... But it is a diagonal... You could output "Diagonal match, left to right"

**Comment by thirdiblind** [comment]
Corrections made. Pushing to repo 6/7pm Central Standard Time 11/13/23
